-- SQLite
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-1');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-1');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-1');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-1');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-2');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-2');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-3');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-3');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M508I-2');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-2');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-3');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-4');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-3');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-4');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-4');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-4');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-5');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M508I-5');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-5');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-5');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-6');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-6');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-6');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-7');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-7');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-7');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-6');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-8');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M508I-8');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-7');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-8');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-9');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-9');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-9');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-10');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-10');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-10');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-8');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-11');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M508I-11');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-9');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-11');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-12');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-12');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-12');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-13');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-13');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-13');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-10');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-14');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-11');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-14');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-15');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-15');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-14');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-16');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-15');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-16');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-16');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-12');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-17');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-13');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-17');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-18');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-18');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-17');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-19');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-18');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-19');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-14');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-20');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-19');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-15');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-21');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-20');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('MACONE Marie','4E5M512I-1');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-21');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-22');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M511I-16');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-22');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-23');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-1');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('BRAIKI Khaoula','4E5M510I-23');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('HYON Emmanuel','4E5M508I-24');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('MACONE Marie','4E5M512I-2');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-20');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('GUEZOU Xavier','4E5M514I-1');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-2');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-3');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('GUEZOU Xavier','4E5M514I-2');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-4');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-5');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('GUEZOU Xavier','4E5M514I-3');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-6');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-7');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('GUEZOU Xavier','4E5M514I-4');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-8');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-9');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-21');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-10');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-11');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('GUEZOU Xavier','4E5M514I-5');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-12');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-13');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ANGARITA AROCHA Rafael','4E5M506I-22');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('GUEZOU Xavier','4E5M514I-6');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-14');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-15');
INSERT INTO enseignants (Enseignant_nom, Code_cours) VALUES ('ISOARD Thierry Michel','4E5M507I-16');
