INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 110','4E5M511I-1','Bat. Allais','80');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI G','4E5M510I-1','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M506I-1','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M508I-1','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M510I-2','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M511I-2','Bat. Allais','50');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI B','4E5M510I-3','Bat. Allais','475');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI F','4E5M511I-3','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M508I-2','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('En cours','4E5M506I-2',' ','0');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M506I-3','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-4','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M508I-3','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213C','4E5M506I-4','Bat. Allais','30');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M508I-4','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M511I-4','Bat. Allais','50');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI G','4E5M510I-5','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M508I-5','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI F','4E5M511I-5','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M506I-5','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M506I-6','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-6','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M508I-6','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M506I-7','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M508I-7','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M510I-7','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M511I-6','Bat. Allais','50');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI G','4E5M510I-8','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M508I-8','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI F','4E5M511I-7','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M506I-8','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213C','4E5M506I-9','Bat. Allais','30');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-9','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M508I-9','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M506I-10','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M508I-10','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M510I-10','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M511I-8','Bat. Allais','50');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI G','4E5M510I-11','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M508I-11','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI F','4E5M511I-9','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M506I-11','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M506I-12','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-12','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M508I-12','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M506I-13','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M508I-13','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M510I-13','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 401/402','4E5M511I-10','Bat. Allais','60');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI G','4E5M510I-14','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI F','4E5M511I-11','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M506I-14','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213C','4E5M506I-15','Bat. Allais','30');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-15','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M508I-14','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M506I-16','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M508I-15','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M508I-16','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-16','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 401/402','4E5M511I-12','Bat. Allais','60');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI G','4E5M510I-17','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI F','4E5M511I-13','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M506I-17','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M506I-18','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-18','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M508I-17','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M506I-19','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M508I-18','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M510I-19','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M511I-14','Bat. Allais','50');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI G','4E5M510I-20','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M508I-19','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI F','4E5M511I-15','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-21','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M508I-20','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M512I-1','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M508I-21','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M510I-22','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 401/402','4E5M511I-16','Bat. Allais','60');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213C','4E5M508I-22','Bat. Allais','30');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M508I-23','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M507I-1','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 214','4E5M510I-23','Bat. Allais','20');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M508I-24','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213B','4E5M512I-2','Bat. Allais','22');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M506I-20','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 310A','4E5M514I-1','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI D','4E5M507I-2','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 512','4E5M507I-3','Bat. Allais','45');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 403','4E5M514I-2','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('N 02','4E5M507I-4','Bat. Ephémère 2','55');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 110','4E5M507I-5','Bat. Allais','80');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 105','4E5M514I-3','Bat. Allais','30');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI G','4E5M507I-6','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 401/402','4E5M507I-7','Bat. Allais','60');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 413B','4E5M514I-4','Bat. Allais','45');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G AMPHI F','4E5M507I-8','Bat. Allais','180');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 104','4E5M507I-9','Bat. Allais','30');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 213A','4E5M506I-21','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M507I-10','Bat. Allais','50');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 503','4E5M507I-11','Bat. Allais','40');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 310A','4E5M514I-5','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 101/102','4E5M507I-12','Bat. Allais','55');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 512','4E5M507I-13','Bat. Allais','45');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 201','4E5M506I-22','Bat. Allais','30');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 403','4E5M514I-6','Bat. Allais','35');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M507I-14','Bat. Allais','50');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M507I-15','Bat. Allais','50');
INSERT INTO Salle (Nom_salle, Code_cours, Batiment, Capacite) VALUES ('G 301/302','4E5M507I-16','Bat. Allais','50');
